// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var MnstrUtils = require("../MnstrUtils.bs.js");
var ExpressPromiseRouter = require("express-promise-router");

function resolve(prim) {
  return Promise.resolve(prim);
}

function make(routes, _) {
  var toMount = Js_option.getWithDefault(/* :: */[
        /* Get */Block.__(0, [
            "/",
            MnstrUtils.Http[/* heartbeat */1]
          ]),
        /* [] */0
      ], routes);
  var router = ExpressPromiseRouter(/* () */0);
  List.iter((function (route) {
          if (route.tag) {
            router.post(route[0], route[1]);
            return /* () */0;
          } else {
            router.get(route[0], route[1]);
            return /* () */0;
          }
        }), toMount);
  return router;
}

var Web = /* module */[/* make */make];

exports.resolve = resolve;
exports.Web = Web;
/* MnstrUtils Not a pure module */
