// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ApolloServerExpress = require("bs-apollo-server-express/src/ApolloServerExpress.js");

var Cors = /* module */[];

var Morgan = /* module */[];

var Json = /* module */[];

var BodyParser = /* module */[/* Json */Json];

var graphiql = ApolloServerExpress.createGraphiQLExpressMiddleware(/* None */0, /* None */0, /* None */0, /* None */0, "/graphql");

var GraphQl = /* module */[/* graphiql */graphiql];

var Express = /* module */[
  /* Cors */Cors,
  /* Morgan */Morgan,
  /* BodyParser */BodyParser,
  /* GraphQl */GraphQl
];

exports.Express = Express;
/* graphiql Not a pure module */
