// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var MnstrUtils = require("./MnstrUtils.bs.js");

var Utils = /* module */[
  /* Text */MnstrUtils.Text,
  /* Promise */MnstrUtils.Promise,
  /* Env */MnstrUtils.Env
];

exports.Utils = Utils;
/* MnstrUtils Not a pure module */
